version: "3.8"
services:
  postgres:
    image: postgres:12.5-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: files_db
    volumes:
      - db-data:/var/lib/postgres

volumes:
  db-data:
    name: postgres